#!/bin/sh
# Run llvm's configure script with customizations necessary for the current
# development host.

scriptname=lli_undef_fix/git/dbin/configure-llvm



case `hostname` in
   dyson)
      PROJ_DIR=/uusoc/scratch/dyson/cas/edu/uut/lli_undef_fix
      host_specific_options=""
      ;;
   *)
      echo error: do not recognize host `hostname`.
      exit -1
      ;;
esac

# TODO2: consider running `gcc --version`, and if version is 4.6, then
# setting --disable-compiler-version-checks. 

# Note: configure's --disable-compiler-version-checks flag doesn't work with
# gcc4.6 because the build process requires compiler support for C++2011.

BUILD_DIR=`pwd`
if find | grep -vEq -e '^\\s*$'; then
   # all appears to be ok
   echo setting up build directory in $BUILD_DIR.
else
   echo ${scriptname}: current directory would be used 
   echo "  " as the build dir, but it does not appear to be empty.
   exit 255
fi

exec $PROJ_DIR/git/llvm/configure --prefix $PROJ_DIR/live \
      $host_specific_options "$@"

# end of script

