#!/bin/sh
# set up a workspace for working on this project
#
# Note: This is heavily customized for Christian Schreiner's home directory
# organization.  Other users will probably want to modify this to their
# tastes.

scriptname=lli_undef_fix_workspace

export PROJ_DIR=$EDUUUT/lli_undef_fix2
if [ ! -d $PROJ_DIR ]; then
   echo ${scriptname}: can not find project directory.
   echo "  " dir=\"$PROJ_DIR\".
   exit 255
fi

if [ ! -d $PROJ_DIR/live/bin ]; then
   echo ${scriptname}: can not find llvm live binary directory.
   echo "  " dir=\"$PROJ_DIR/live/bin\".
   exit 255
fi
export PATH=$PROJ_DIR/live/bin:$PATH

cd $PROJ_DIR/git/llvm
workspace soft

# ==========================================================================
# extra windows customized for this project

# these are currently customized for dyson, rethink them for other hosts.
left_monitor_width=1680
left_monitor_height=1050
right_monitor_width=1280
right_monitor_height=1024

xterm -sb -title "vmstat xterm" -geometry 82x25+$left_monitor_width-0 \
      -e "vmstat 5" &

# TODO2: add something here for the web browser window
firefox http://www.llvm.org/docs/GettingStarted.html \
      http://llvm.org/docs/LangRef.html \
      &


# ==========================================================================
# end of script

